[package]
name = "traclus"
version = "0.1.0"
authors = ["gu18168 <gu18168@gmail.com>"]
edition = "2018"

[[bin]]
name = "traclus"
path = "src/main.rs"

[dependencies]
rayon = "1.0.3"
uuid = { version = "0.7.2", features = ["v4"] }